name: automerge-feat
on:
  push:
    branches:
      - 'master'

jobs:
  automerge-feat:
    runs-on: ubuntu-16.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@master
      - name: Merge to feat/expressive-sunset
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'feat/expressive-sunset'
        env:
          GITHUB_TOKEN: ${{secrets.MERGE_ACTION}}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
