name: automerge-mastheadv2
on:
  push:
    branches:
      - 'main'

concurrency:
  group: automerge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  automerge-mastheadv2:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Merge to feat/masthead-v2
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: 'feat/masthead-v2'
        env:
          GITHUB_TOKEN: ${{secrets.MERGE_ACTION}}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
