name: automerge
on:
  push:
    branches: [ release/* ]

concurrency:
  group: automerge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  automerge:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Merge to main
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: 'main'
        env:
          GITHUB_TOKEN: ${{secrets.MERGE_ACTION}}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
