name: Auto approve

on:
  pull_request_target:
    branches:
      - test/e2e-percy-baseline

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: ${{ github.actor == 'ibmdotcom-bot' }}
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
