name: ci-check

on: [push, pull_request]

jobs:
  check-packages:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: ['12.x']
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn build
      - name: Run CI Checks
        run: |
          yarn ci-check
          yarn lerna run --ignore=@carbon/ibmdotcom-web-components --max-buffer=200000000 ci-check
  web-components:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: ['12.x']
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn build
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Run basic checks
        run: xvfb-run --auto-servernum yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-web-components ci-check
  a11y:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: ['12.x']
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn build
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Run a11y compliance tests
        run: xvfb-run --auto-servernum --error-file=/dev/stderr yarn test:a11y || true
  integration-build-bundle:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: ['12.x']
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Build
        run: yarn build
      - name: Run build integration test (React)
        run: xvfb-run --auto-servernum yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-react test:integration:build
        env:
          DDS_BUILD_INTEGRATION_TEST_NAVIGATION_TIMEOUT: 60000
          DDS_BUILD_INTEGRATION_TEST_TIMEOUT: 60000
      - name: Run build integration test (Web Components)
        run: xvfb-run --auto-servernum yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-web-components test:integration:build
        env:
          DDS_BUILD_INTEGRATION_TEST_NAVIGATION_TIMEOUT: 60000
          DDS_BUILD_INTEGRATION_TEST_TIMEOUT: 60000
      - name: Run bundle integration test (React)
        run: yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-react test:integration:bundle
