name: ci-check

on:
  push:
    branches: [ main, release/*, feat/cwc-v2, fix/content-updates ]
  pull_request:
    branches: [ main, release/*, feat/cwc-v2, fix/content-updates ]

concurrency:
  group: ci-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-packages:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-web-components --ignore @carbon/ibmdotcom-services-store build
      - name: Run CI Checks
        run: |
          yarn ci-check
          yarn lerna run --stream --ignore=@carbon/ibmdotcom-web-components ci-check
  web-components:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Run basic checks
        run: xvfb-run --auto-servernum yarn lerna run --stream --prefix --scope=@carbon/ibmdotcom-web-components ci-check
  a11y:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn build
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Run a11y compliance tests
        run: xvfb-run --auto-servernum --error-file=/dev/stderr yarn test:a11y
