name: ci-check

on:
  push:
    branches: [ main, release/*, feat/*, fix/content-updates ]
  pull_request:
    branches: [ main, release/*, feat/*, fix/content-updates ]

concurrency:
  group: ci-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-packages:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.15
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-web-components --ignore @carbon/ibmdotcom-services-store build
      - name: Run CI Checks
        run: |
          yarn ci-check
          yarn lerna run --ignore=@carbon/ibmdotcom-web-components ci-check
  web-components:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.15
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn lerna run --stream build
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Run basic checks
        run: xvfb-run --auto-servernum yarn lerna run --stream --prefix --verbose --scope=@carbon/ibmdotcom-web-components ci-check
