name: Deploy @carbon/ibmdotcom-elements storybook to IBM Cloud (Canary)

on:
  push:
    branches:
      - master

jobs:
  deploy-elements-to-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn build
      - name: Install IBM Cloud CLI
        uses: ./.github/actions/install-ibmcloud-cli
      - name: Logging into IBM Cloud
        uses: ./.github/actions/login-ibmcloud
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
      - name: Building @carbon/ibmdotcom-elements storybook
        env:
          CORS_PROXY: ${{ secrets.CORS_PROXY }}
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
        run: |
          cd packages/elements
          yarn build-storybook
      - name: Deploying @carbon/ibmdotcom-elements storybook to IBM Cloud
        uses: ./.github/actions/deploy-ibmcloud
        with:
          cf-app: ibmdotcom-elements-canary
          cf-manifest: manifest-canary.yml
