name: deploy-staging (Deploy storybook environments to IBM Cloud)

on:
  push:
    branches:
      - release/*

jobs:
  react:
    runs-on: ubuntu-16.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/react/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
      - name: Building @carbon/ibmdotcom-react storybook
        run: yarn build-storybook
        working-directory: packages/react
      - name: Deploying @carbon/ibmdotcom-react (staging) storybook to IBM Cloud
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-react-staging
          cf-manifest: manifest-staging.yml
          deploy-dir: packages/react
      - name: Set env vars for e2e percy snapshots
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/tests-e2e/.env
        env:
          SELENIUM_HOST: https://ibmdotcom-react-staging.mybluemix.net
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_REACT_E2E }}
      - name: Create e2e percy snapshots
        run: yarn test:e2e
        working-directory: packages/tests-e2e
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
  web-components:
    runs-on: ubuntu-16.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
      - name: Building @carbon/ibmdotcom-web-components (staging) storybook
        run: yarn build-storybook
        working-directory: packages/web-components
      - name: Deploying @carbon/ibmdotcom-web-components (staging) storybook to IBM Cloud
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-web-components-staging
          cf-manifest: manifest-staging.yml
          deploy-dir: packages/web-components
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
