name: deploy-next (Deploy storybook environments to Github Pages)

on:
  push:
    branches:
      - release/*

concurrency:
  group: deploy-next-${{ github.ref }}
  cancel-in-progress: true

jobs:
  carbon-web-components:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.MERGE_ACTION}}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn lerna run --scope @carbon/web-components build

      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/carbon-web-components/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
      - name: Building @carbon/web-components (next) storybook
        run: yarn build-storybook
        working-directory: packages/carbon-web-components
      - name: Move storybook to build folder
        run: |
          rm packages/carbon-web-components/.env
          mkdir -p builds
          mv packages/carbon-web-components/storybook-static builds/carbon-web-components

      - name: Deploying @carbon/web-components (next) storybook to Github Pages
        run: |
          git config --global user.email ${{ secrets.BOT_EMAIL }}
          git config --global user.name ${{ secrets.BOT_NAME }}

          git fetch origin gh-pages
          git checkout -b gh-pages origin/gh-pages
          git update-ref -d refs/remotes/origin/gh-pages
          git pull origin gh-pages

          rm -rf next/carbon-web-components
          mkdir -p next
          mv builds/carbon-web-components next/carbon-web-components

          git add next/carbon-web-components
          git commit -m "chore(deploy): deploy Carbon web components next to GitHub Pages"
          git push origin gh-pages
      - uses: act10ns/slack@v2
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
  react:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.MERGE_ACTION}}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn lerna run build

      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/react/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
      - name: Building @carbon/ibmdotcom-react storybook
        run: yarn build-storybook
        working-directory: packages/react
      - name: Move storybook to build folder
        run: |
          rm packages/react/.env
          mkdir -p builds
          mv packages/react/storybook-static builds/react

      - name: Set env vars (RTL)
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/react/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
      - name: Building @carbon/ibmdotcom-react (RTL) storybook
        run: yarn build-storybook:rtl
        working-directory: packages/react
      - name: Move storybook to build folder
        run: |
          rm packages/react/.env
          mv packages/react/storybook-static-rtl builds/react-rtl

      - name: Deploying @carbon/ibmdotcom-react (next) storybook to Github Pages
        run: |
          git config --global user.email ${{ secrets.BOT_EMAIL }}
          git config --global user.name ${{ secrets.BOT_NAME }}

          git fetch origin gh-pages
          git checkout -b gh-pages origin/gh-pages
          git update-ref -d refs/remotes/origin/gh-pages
          git pull origin gh-pages

          rm -rf next/react
          rm -rf next/react-rtl
          mkdir -p next
          mv builds/react next/react
          mv builds/react-rtl next/react-rtl

          git add next/react
          git add next/react-rtl
          git commit -m "chore(deploy): deploy React next to GitHub Pages"
          git push origin gh-pages
      - uses: act10ns/slack@v2
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
  web-components:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.MERGE_ACTION}}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn lerna run --ignore @carbon/ibmdotcom-react build

      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
      - name: Building @carbon/ibmdotcom-web-components (next) storybook
        run: yarn build-storybook
        working-directory: packages/web-components
      - name: Move storybook to build folder
        run: |
          rm packages/web-components/.env
          mkdir -p builds
          mv packages/web-components/storybook-static builds/web-components

      - name: Set env vars (RTL)
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
      - name: Building @carbon/ibmdotcom-web-components RTL storybook
        run: yarn build-storybook:rtl
        working-directory: packages/web-components
      - name: Move storybook to build folder
        run: |
          rm packages/web-components/.env
          mv packages/web-components/storybook-static-rtl builds/web-components-rtl

      - name: Set env vars (react wrapper)
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
          DDS_FLAGS_ALL: true
      - name: Building @carbon/ibmdotcom-web-components react wrapper storybook
        run: yarn build-storybook:react
        working-directory: packages/web-components
      - name: Move storybook to build folder
        run: |
          rm packages/web-components/.env
          mv packages/web-components/storybook-static-react builds/web-components-react

      - name: Deploying @carbon/ibmdotcom-web-components (next) storybook to Github Pages
        run: |
          git config --global user.email ${{ secrets.BOT_EMAIL }}
          git config --global user.name ${{ secrets.BOT_NAME }}

          git fetch origin gh-pages
          git checkout -b gh-pages origin/gh-pages
          git update-ref -d refs/remotes/origin/gh-pages
          git pull origin gh-pages

          rm -rf next/web-components
          rm -rf next/web-components-rtl
          rm -rf next/web-components-react
          mkdir -p next
          mv builds/web-components next/web-components
          mv builds/web-components-rtl next/web-components-rtl
          mv builds/web-components-react next/web-components-react

          git add next/web-components
          git add next/web-components-rtl
          git add next/web-components-react
          git commit -m "chore(deploy): deploy Web Components next to GitHub Pages"
          git push origin gh-pages
      - uses: act10ns/slack@v2
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
