name: deploy-canary (Deploy storybook environments to IBM Cloud)

on:
  push:
    branches:
      - master

concurrency:
  group: deploy-canary-${{ github.ref }}
  cancel-in-progress: true

jobs:
  react:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-web-components --ignore @carbon/ibmdotcom-services-store build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/react/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
      - name: Building @carbon/ibmdotcom-react storybook
        run: yarn build-storybook
        working-directory: packages/react
      - name: Deploying @carbon/ibmdotcom-react storybook to IBM Cloud
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-react-canary
          cf-manifest: manifest-canary.yml
          deploy-dir: packages/react
  react-experimental:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-web-components --ignore @carbon/ibmdotcom-services-store build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/react/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
          DDS_FLAGS_ALL: true
      - name: Building @carbon/ibmdotcom-react (experimental) storybook
        run: yarn build-storybook
        working-directory: packages/react
      - name: Deploying @carbon/ibmdotcom-react (experimental) storybook to IBM Cloud
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-react-experimental
          cf-manifest: manifest-experimental.yml
          deploy-dir: packages/react
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
  react-rtl:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-web-components --ignore @carbon/ibmdotcom-services-store build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/react/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
          REACT_STORYBOOK_USE_RTL: true
      - name: Building @carbon/ibmdotcom-react (RTL) storybook
        run: yarn build-storybook
        working-directory: packages/react
      - name: Deploying @carbon/ibmdotcom-react (RTL) storybook to IBM Cloud
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-react-rtl
          cf-manifest: manifest-rtl.yml
          deploy-dir: packages/react
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
  web-components:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
      - name: Building @carbon/ibmdotcom-web-components storybook
        run: yarn build-storybook
        working-directory: packages/web-components
      - name: Deploying @carbon/ibmdotcom-web-components storybook to IBM Cloud
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-web-components-canary
          cf-manifest: manifest-canary.yml
          deploy-dir: packages/web-components
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
  web-components-rtl:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
          STORYBOOK_IBMDOTCOM_WEB_COMPONENTS_USE_RTL: true
      - name: Building @carbon/ibmdotcom-web-components RTL storybook
        run: yarn build-storybook
        working-directory: packages/web-components
      - name: Deploying @carbon/ibmdotcom-web-components RTL storybook to IBM Cloud
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-web-components-rtl
          cf-manifest: manifest-rtl.yml
          deploy-dir: packages/web-components
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
  web-components-experimental:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
          DDS_FLAGS_ALL: true
      - name: Building @carbon/ibmdotcom-web-components experimental storybook
        run: yarn build-storybook
        working-directory: packages/web-components
      - name: Deploying @carbon/ibmdotcom-web-components experimental storybook to IBM Cloud
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-web-components-experimental
          cf-manifest: manifest-experimental.yml
          deploy-dir: packages/web-components
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
  web-components-react:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
      - name: Building @carbon/ibmdotcom-web-components react wrapper storybook
        run: yarn build-storybook:react
        working-directory: packages/web-components
      - name: Deploying @carbon/ibmdotcom-web-components react wrapper storybook to IBM Cloud
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-web-components-react
          cf-manifest: manifest-react.yml
          deploy-dir: packages/web-components
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
  services:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react --ignore @carbon/ibmdotcom-web-components --ignore @carbon/ibmdotcom-services-store build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/services/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PROFILE_HOST: ${{ secrets.PROFILE_HOST }}
      - name: Building @carbon/ibmdotcom-services JSDocs
        run: yarn jsdoc
        working-directory: packages/services
      - name: Deploying @carbon/ibmdotcom-services JSDocs to IBM Cloud
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-services
          cf-manifest: manifest.yml
          deploy-dir: packages/services
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
  utilities:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn lerna run --scope @carbon/ibmdotcom-utilities build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/utilities/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
      - name: Building @carbon/ibmdotcom-utilities JSDocs
        run: yarn jsdoc
        working-directory: packages/utilities
      - name: Deploying @carbon/ibmdotcom-utilities JSDocs to IBM Cloud
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-utilities
          cf-manifest: manifest.yml
          deploy-dir: packages/utilities
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
