name: e2e-tests

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main, release/* ]
  pull_request_target:
    types: [opened,closed,synchronize]

concurrency:
  group: e2e-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  
  install-web-components:
    strategy:
      matrix:
        os: [ macos-latest ]
        node-version: [ 14.x ]
        browser: [ chromium ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'


      - uses: actions/cache@v2
        name: Yarn cache
        id: yarn-cache
        with:
          path: |
            **/node_modules
            /Users/runner/Library/Caches/Cypress
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn









      - name: Installing dependencies (if not cached)
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --offline


      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build








      - name: Set Cloud Masthead env var
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          DDS_CLOUD_MASTHEAD: true
      - name: Build storybook
        working-directory: packages/web-components
        run: yarn build-storybook
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: storybook-build
          path: packages/web-components/storybook-static


  web-components-tests:
    runs-on: macos-latest
    needs: install-web-components
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
        os: [ macos-latest ]
        node-version: [ 14.x ]
        browser: [ chromium ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'        

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: storybook-build
          path: packages/web-components/storybook-static


      # this retrieves the saved cache from the install job
      - uses: actions/cache@v2
        name: yarn-cache
        id: yarn-cache
        with:
          path: |
            **/node_modules
            /Users/runner/Library/Caches/Cypress
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - run: yarn cypress install --force
        
      - name: 'Run e2e tests (chromium)'
        uses: cypress-io/github-action@v4
        with:
          working-directory: packages/web-components
          config-file: tests/e2e-storybook/cypress.json
          start: yarn test:e2e-storybook:test
          install: false
          browser: chrome
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_CACHE_FOLDER: /Users/runner/Library/Caches/Cypress

#
