name: e2e-tests

on:
  push:
    branches: [ main, release/*, feat/cwc-v2, fix/content-updates ]
  pull_request:
    branches: [ main, release/*, feat/cwc-v2, fix/content-updates ]

concurrency:
  group: e2e-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-components:
    strategy:
      matrix:
        os: [ macos-latest ]
        node-version: [ 14.x ]
        browser: [ chromium ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build
      - name: Set Cloud Masthead env var
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          DDS_CLOUD_MASTHEAD: true
          DDS_FLAGS_ALL: true
      - name: Build storybook
        working-directory: packages/web-components
        run: yarn build-storybook
      - name: Run e2e tests (chromium)
        if: matrix.browser == 'chromium'
        working-directory: packages/web-components
        run: yarn test:e2e-storybook:test:no-percy
  react:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 14.x ]
        browser: [ chromium ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-web-components --ignore @carbon/ibmdotcom-services-store build
      - name: Build storybook
        working-directory: packages/react
        run: yarn build-storybook
      - name: Run e2e tests (chromium)
        if: matrix.browser == 'chromium'
        working-directory: packages/react
        run: yarn test:e2e-storybook:test:no-percy
