name: e2e-tests

on:
  push:
    branches: [ master, release/* ]
  pull_request:
    branches: [ master, release/* ]

concurrency:
  group: e2e-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-components:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        node-version: [ 14.x ]
        browser: [ chromium, firefox ]
        exclude:
          - os: ubuntu-latest
            browser: chromium
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build
      - name: Build storybook
        working-directory: packages/web-components
        run: yarn build-storybook
      - name: Run e2e tests (chromium)
        if: matrix.browser == 'chromium'
        working-directory: packages/web-components
        run: yarn test:e2e-storybook:test:no-percy
      - name: Run e2e tests (firefox)
        if: matrix.browser == 'firefox'
        working-directory: packages/web-components
        run: yarn test:e2e-storybook:test:no-percy:firefox
