name: e2e-tests

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main, release/* ]

concurrency:
  group: e2e-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:

  install:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
  
  
  install-web-components:
    runs-on: ${{ matrix.os }}
    needs: install
    steps:
      - name: Build project
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build
      - name: Set Cloud Masthead env var
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          DDS_CLOUD_MASTHEAD: true
      - name: Build storybook
        working-directory: packages/web-components
        run: yarn build-storybook


  web-components-tests:
    runs-on: ${{ matrix.os }}
    needs: install-web-components
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
        node-version: [ 14.x ]
        browser: [ chromium ]
        containers: [1, 2, 3, 4, 5]
    timeout-minutes: 120
    runs-on: ${{ matrix.os }}
      - name: Run e2e tests (chromium)
        if: matrix.browser == 'chromium'
        working-directory: packages/web-components
        run: yarn test:e2e-storybook:test:no-percy