name: e2e-tests

on:
  push:
    branches: [ main, release/*, feat/*, fix/content-updates ]
  pull_request:
    branches: [ main, release/*, feat/*, fix/content-updates ]

concurrency:
  group: e2e-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-components:
    strategy:
      matrix:
        os: [ macos-latest ]
        node-version: [ 18.x ]
        browser: [ chromium ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn lerna run --stream build
      - name: Set Cloud Masthead env var
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          C4D_CLOUD_MASTHEAD: true
          C4D_FLAGS_ALL: true
      - name: Build storybook
        working-directory: packages/web-components
        run: yarn build-storybook
      - name: Run e2e tests (chromium)
        if: matrix.browser == 'chromium'
        working-directory: packages/web-components
        run: yarn test:e2e-storybook:test:no-percy
