name: e2e-tests-browserstack-canary (run nightly tests on Browserstack Automate)

on:
  schedule:
    - cron: '0 20 * * 1-5'

concurrency:
  group: e2e-tests-browserstack-canary-${{ github.ref }}
  cancel-in-progress: true

jobs:
  react:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: macos-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Run browserstack automate
        working-directory: packages/react
        run: yarn test:e2e-storybook:browserstack:canary --username ${{ secrets.BROWSERSTACK_USER }} --key ${{ secrets.BROWSERSTACK_ACCESSKEY }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
  web-components:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --offline
      - name: Run browserstack automate
        working-directory: packages/web-components
        run: yarn test:e2e-storybook:browserstack:canary --username ${{ secrets.BROWSERSTACK_USER }} --key ${{ secrets.BROWSERSTACK_ACCESSKEY }}
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
