name: percy-update-base

on:
  push:
    branches: [ main, release/*, chore/import-cwc-repo ]

concurrency:
  group: percy-update-base-${{ github.ref }}
  cancel-in-progress: true

jobs:
  react-storybook:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['14.x']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Build
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-services-store --ignore @carbon/ibmdotcom-web-components build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/react/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_REACT }}
      - name: Run percy storybook
        run: yarn build-storybook && yarn visual-snapshot
        working-directory: packages/react
  react-storybook-e2e:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ '14.x' ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Build
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-services-store --ignore @carbon/ibmdotcom-web-components build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/react/.env
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_REACT_E2E }}
      - name: Run e2e tests
        run: yarn build-storybook && yarn test:e2e-storybook:test
        working-directory: packages/react
  web-components:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['14.x']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Install xvfb
        run: sudo apt-get install xvfb
      - name: Build
        run: yarn lerna run --stream --ignore @carbon/ibmdotcom-react build
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: packages/web-components/.env
        env:
          KALTURA_PARTNER_ID: ${{ secrets.KALTURA_PARTNER_ID }}
          KALTURA_UICONF_ID: ${{ secrets.KALTURA_UICONF_ID }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_WEBCOMPONENTS }}
      - name: Run percy storybook
        run: yarn build-storybook && yarn visual-snapshot
        working-directory: packages/web-components
