name: publish-staging (Trigger staging environments to update)

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: publish-staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom'
    runs-on: ubuntu-20.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Deploy NextJS Staging
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: carbon-design-system/carbon-for-ibm-dotcom-nextjs-test
          token: ${{ secrets.GH_DISPATCH_TOKEN }}
          event-type: deploy-staging
      - name: Deploy Web Components HTML Staging
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: carbon-design-system/carbon-for-ibm-dotcom-web-components-test
          token: ${{ secrets.GH_DISPATCH_TOKEN }}
          event-type: deploy-staging
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
